execute:
  freeze: auto

project:
  type: book
  output-dir: _output

book:
  title: "Storm Impact Harmonisation"
  subtitle: "Linking CERF allocations with cyclone population exposure"
  author: "**OCHA Data Science Unit:** Arno Z., Downing T., Ker H., Ndirangu P., Martini G., Milano L."
  sidebar:
    logo: logo_white.png
  chapters:
    - index.qmd
    - 01-data-merge.qmd
    - 02-analysis.qmd
    - part: "Appendices"
      chapters:
        - 03-appendix-adam-gdacs.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: custom.css
